export { default as MainHeader} from "./MainHeader";
export { default as ProfilPage} from "./ProfilPage";
export { default as LoadingPage} from "./LoadingPage";
export { default as HomePage} from "./HomePage";
export { default as AddressPage} from "./AddressPage";
export { default as MidtermsPage} from "./MidtermsPage";
export { default as BlogPage} from "./BlogPage";
export { default as InfoPage} from "./InfoPage";
export { default as MakeUpsPage} from "./MakeUpsPage";